// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient } from "npm:@supabase/supabase-js@^2.74.0";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Qui\xE9n soy",
  description: "Devuelve el usuario autenticado, su rol global y las membres\xEDas por edificio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = sb(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }, { data: memberships }] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId),
      supabase.from("building_memberships").select("*").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles ?? []).map((r) => r.role),
      memberships: memberships ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-buildings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.74.0";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_buildings_default = defineTool2({
  name: "list_buildings",
  title: "Listar edificios",
  description: "Lista los edificios a los que el usuario autenticado tiene acceso (por RLS).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("buildings_new").select("id, name, address, org_id, created_at").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { buildings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-units.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.74.0";
import { z } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_units_default = defineTool3({
  name: "list_units",
  title: "Listar unidades",
  description: "Lista las unidades/apartamentos de un edificio.",
  inputSchema: {
    building_id: z.string().uuid().describe("ID del edificio (buildings_new.id)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ building_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("units").select("*").eq("building_id", building_id).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { units: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tickets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_tickets_default = defineTool4({
  name: "list_tickets",
  title: "Listar tickets",
  description: "Lista los tickets de mantenimiento de un edificio, opcionalmente filtrados por estado.",
  inputSchema: {
    building_id: z2.string().uuid().describe("ID del edificio"),
    status: z2.string().optional().describe("Estado opcional (open, in_progress, resolved, closed)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ building_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let query = sb4(ctx).from("tickets").select("*").eq("building_id", building_id).order("created_at", { ascending: false }).limit(100);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-ticket.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_ticket_default = defineTool5({
  name: "create_ticket",
  title: "Crear ticket",
  description: "Crea un ticket de mantenimiento en un edificio.",
  inputSchema: {
    building_id: z3.string().uuid().describe("ID del edificio"),
    title: z3.string().trim().min(1).max(200).describe("T\xEDtulo del ticket"),
    description: z3.string().trim().min(1).max(2e3).describe("Descripci\xF3n del problema"),
    priority: z3.enum(["low", "medium", "high", "urgent"]).optional().describe("Prioridad opcional")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ building_id, title, description, priority }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await sb5(ctx).from("tickets").insert({
      building_id,
      title,
      description,
      priority: priority ?? "medium",
      created_by: ctx.getUserId(),
      status: "open"
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { ticket: data }
    };
  }
});

// src/lib/mcp/tools/list-amenities.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb6(ctx) {
  return createClient6(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_amenities_default = defineTool6({
  name: "list_amenities",
  title: "Listar amenidades",
  description: "Lista las amenidades (piscina, gimnasio, etc.) de un edificio.",
  inputSchema: {
    building_id: z4.string().uuid().describe("ID del edificio")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ building_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await sb6(ctx).from("amenities").select("*").eq("building_id", building_id).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { amenities: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nlkrylgakpugonsvnycj";
var mcp_default = defineMcp({
  name: "proppass-mcp",
  title: "PropPass MCP",
  version: "0.1.0",
  instructions: "Herramientas para PropPass, la plataforma de gesti\xF3n de edificios residenciales. Usa `whoami` para verificar el usuario, `list_buildings` para descubrir edificios, y las dem\xE1s herramientas para consultar unidades, amenidades y tickets, o crear tickets nuevos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_buildings_default,
    list_units_default,
    list_tickets_default,
    create_ticket_default,
    list_amenities_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
